DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS sound;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  first_login INTEGER NOT NULL
);

CREATE TABLE sound (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user (id)
);
